version: '3.8'

services:
  json-builder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resume-export-container-compose
    volumes:
      - my_volume:/app/result

  nginx-resume:
    depends_on:
      - json-builder
    image: nginx:1.23.2-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - my_volume:/usr/share/nginx/html/
volumes:
  my_volume: