version: '3.8'

services:
  html-builder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resume-export-container-compose
    volumes:
      - my_volume:/app/result

  nginx-resume-worker:
    depends_on:
      - html-builder
    image: nginx:1.23.2-alpine
    deploy:
      replicas: 3
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - my_volume:/usr/share/nginx/html/
    networks:
      - nginx_network

  nginx-resume-balancer:
    depends_on:
      - nginx-resume-worker
    image: nginx:1.23.2-alpine
    ports:
      - "8080:80"
    volumes:
      - ./balancer.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nginx_network

volumes:
  my_volume:
networks:
  nginx_network: