version: '3'
env:
  THEME: '{{ .THEME | default "jsonresume-theme-stackoverflow" }}'
  PROJECT: '{{ .PROJECT | default "resume" }}'
tasks:
  json:
    cmds:
      - python Resume_json.py
  html:
    deps:
      - json
    cmds:
      - npm install {{ .THEME }}
      - resume export --format html --theme {{ .THEME }} resume.html
  compose-up:
    cmds:
      - docker-compose -p {{ .PROJECT }} up -d
  compose-down:
    cmds:
      - docker-compose -p {{ .PROJECT }} down -v
  docker-builder:
    cmds:
      - docker build -t {{ .PROJECT }}-builder --target builder .    
  docker-release:
    deps:
      - docker-builder
    cmds:
      - docker build -t {{ .PROJECT }}-release . 
  docker-build:
    cmds:
      - task: docker-builder
      - task: docker-release
  docker-run:
    cmds:
      - docker run --rm -ti --name "{{ .PROJECT }}-export" -d {{ .PROJECT }}-release
  docker-stop:
    cmds:
      - docker stop {{ .PROJECT }}-export