name: CI 

on:
 workflow_dispatch:
  inputs:
   tag:
    description: 'Image tag'
    default: 'latest'
 push:
  branches:
   - "*"

jobs:
  build-builder:
    runs-on: ubuntu-latest
    env:
        TAG: "${{ inputs.tag != '' && inputs.tag || github.ref_name }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build builder image and push
        uses: docker/build-push-action@v5
        with:
          context: ./module2 - git
          file: ./module2 - git/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/resume-builder:${{ env.TAG }}
          target: builder
          
      - name: Build release image and push
        uses: docker/build-push-action@v3
        with:
          context: ./module2 - git
          file: ./module2 - git/Dockerfile
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/resume-release:${{ env.TAG }}
